# Generated by Django 3.1 on 2020-09-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
    ]
